# Generated by Django 2.2.23 on 2021-05-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('finishTime', models.CharField(max_length=50)),
                ('reportedDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
