# Generated by Django 2.2.23 on 2021-05-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shephy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='finishTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='reportedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
